name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install
        working-directory: ./functions

      - name: Set Firebase Environment Config for SMTP
        run: npx firebase-tools functions:config:set smtp.email="${{ secrets.SMTP_EMAIL }}" smtp.pass="${{ secrets.SMTP_PASS }}" --project ${{ secrets.FIREBASE_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only functions --project ${{ secrets.FIREBASE_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }} --non-interactive
